-- ReplicatedStorage/Localization/LocalizationKeys.lua
-- Single source of truth for ALL localization keys.

local LocalizationKeys = {}

LocalizationKeys.Keys = {
	
	-- LOCKED TERMS (never translated)
	LOCK_SAFE = "LOCK_SAFE",
	LOCK_OUT = "LOCK_OUT",
	LOCK_ROUND_KING = "LOCK_ROUND_KING",

	-- GLOBAL / UI
	UI_MODE_RANKED = "UI_MODE_RANKED",
	UI_MODE_CASUAL = "UI_MODE_CASUAL",
	UI_MODE_TRAINING = "UI_MODE_TRAINING",

	UI_YES = "UI_YES",
	UI_NO = "UI_NO",
	UI_CONFIRM = "UI_CONFIRM",
	UI_CANCEL = "UI_CANCEL",
	UI_CLOSE = "UI_CLOSE",
	UI_BACK = "UI_BACK",
	UI_CONTINUE = "UI_CONTINUE",

	-- MATCH FLOW
	MATCH_WAITING_FOR_PLAYERS = "MATCH_WAITING_FOR_PLAYERS",
	MATCH_STARTING = "MATCH_STARTING",
	MATCH_STARTED = "MATCH_STARTED",
	MATCH_ABORTED = "MATCH_ABORTED",
	MATCH_FINISHED = "MATCH_FINISHED",

	MATCH_ABORT_REASON_FORFEIT_RATIO = "MATCH_ABORT_REASON_FORFEIT_RATIO",
	MATCH_ABORT_REASON_1V1 = "MATCH_ABORT_REASON_1V1",
	MATCH_ABORT_REASON_INVALID_TELEPORT = "MATCH_ABORT_REASON_INVALID_TELEPORT",

	MATCH_WINNER_ANNOUNCEMENT = "MATCH_WINNER_ANNOUNCEMENT",
	MATCH_ROUND_KING_ANNOUNCEMENT = "MATCH_ROUND_KING_ANNOUNCEMENT",

	-- ROUND SYSTEM
	ROUND_COUNTER = "ROUND_COUNTER",
	ROUND_STARTING = "ROUND_STARTING",
	ROUND_ACTIVE = "ROUND_ACTIVE",
	ROUND_FINISHED = "ROUND_FINISHED",
	ROUND_ADVANCING = "ROUND_ADVANCING",

	COUNTDOWN_3 = "COUNTDOWN_3",
	COUNTDOWN_2 = "COUNTDOWN_2",
	COUNTDOWN_1 = "COUNTDOWN_1",
	COUNTDOWN_START = "COUNTDOWN_START",

	-- SAFE / OUT / SPECTATOR
	PLAYER_SAFE = "PLAYER_SAFE",
	PLAYER_OUT = "PLAYER_OUT",
	PLAYER_SPECTATOR = "PLAYER_SPECTATOR",

	SAFE_POPUP = "SAFE_POPUP",
	SAFE_CROWN = "SAFE_CROWN",
	SAFE_LIST_ENTRY = "SAFE_LIST_ENTRY",

	OUT_IMPACT = "OUT_IMPACT",
	OUT_SPECTATING = "OUT_SPECTATING",

	SPECTATOR_MODE_ACTIVE = "SPECTATOR_MODE_ACTIVE",
	SPECTATOR_WAITING_NEXT_ROUND = "SPECTATOR_WAITING_NEXT_ROUND",

	-- LEAVE / FORFEIT
	LEAVE_CONFIRM_TITLE = "LEAVE_CONFIRM_TITLE",
	LEAVE_CONFIRM_BODY = "LEAVE_CONFIRM_BODY",
	LEAVE_CONFIRM_ACTIVE_WARNING = "LEAVE_CONFIRM_ACTIVE_WARNING",
	LEAVE_CONFIRM_SPECTATOR = "LEAVE_CONFIRM_SPECTATOR",
	LEAVE_BUTTON = "LEAVE_BUTTON",

	FORFEIT_NOTICE = "FORFEIT_NOTICE",
	FORFEIT_NO_REWARD = "FORFEIT_NO_REWARD",

	-- STATS / LEADERBOARD
	STATS_ROUNDS_SURVIVED = "STATS_ROUNDS_SURVIVED",
	STATS_MATCH_WINS = "STATS_MATCH_WINS",
	STATS_ROUND_KINGS = "STATS_ROUND_KINGS",

	LEADERBOARD_ALL_TIME = "LEADERBOARD_ALL_TIME",
	LEADERBOARD_DAILY = "LEADERBOARD_DAILY",
	LEADERBOARD_REFRESHING = "LEADERBOARD_REFRESHING",
	LEADERBOARD_POSITION = "LEADERBOARD_POSITION",
	LEADERBOARD_EMPTY = "LEADERBOARD_EMPTY",

	-- RANK SYSTEM
	RANK_CURRENT = "RANK_CURRENT",
	RANK_RP = "RANK_RP",
	RANK_SEASON = "RANK_SEASON",

	RANK_RP_GAINED = "RANK_RP_GAINED",
	RANK_RP_LOST = "RANK_RP_LOST",
	RANK_RP_NOT_ELIGIBLE = "RANK_RP_NOT_ELIGIBLE",
	RANK_LEGEND_FLOOR = "RANK_LEGEND_FLOOR",

	-- TRAINING
	TRAINING_MODE_BADGE = "TRAINING_MODE_BADGE",
	TRAINING_START = "TRAINING_START",
	TRAINING_PICKER_MODE = "TRAINING_PICKER_MODE",
	TRAINING_RANDOM_MODE = "TRAINING_RANDOM_MODE",

	TRAINING_RESULT_WIN = "TRAINING_RESULT_WIN",
	TRAINING_RESULT_LOSE = "TRAINING_RESULT_LOSE",
	TRAINING_RESULT_TIMEOUT = "TRAINING_RESULT_TIMEOUT",

	TRAINING_BEST_TIME = "TRAINING_BEST_TIME",
	TRAINING_NEW_BEST_TIME = "TRAINING_NEW_BEST_TIME",

	-- LOBBY
	LOBBY_WELCOME = "LOBBY_WELCOME",
	LOBBY_MATCH_PAD = "LOBBY_MATCH_PAD",
	LOBBY_TRAINING_PAD = "LOBBY_TRAINING_PAD",

	LOBBY_PAD_PLAYERS = "LOBBY_PAD_PLAYERS",
	LOBBY_PAD_COUNTDOWN = "LOBBY_PAD_COUNTDOWN",
	LOBBY_PAD_FULL_STARTING = "LOBBY_PAD_FULL_STARTING",

	LOBBY_TELEPORTING = "LOBBY_TELEPORTING",
	LOBBY_TELEPORT_FAILED = "LOBBY_TELEPORT_FAILED",
	LOBBY_RETURNED_FROM_GAME = "LOBBY_RETURNED_FROM_GAME",

	-- SYSTEM
	SYSTEM_TELEPORT_INVALID = "SYSTEM_TELEPORT_INVALID",
	SYSTEM_JOIN_TIMEOUT = "SYSTEM_JOIN_TIMEOUT",
	SYSTEM_EXPECTED_PLAYERS_MISSING = "SYSTEM_EXPECTED_PLAYERS_MISSING",
	SYSTEM_SERVER_ERROR = "SYSTEM_SERVER_ERROR",

	-- DEV
	DEV_FORCE_CHALLENGE = "DEV_FORCE_CHALLENGE",
	DEV_SKIP_COUNTDOWN = "DEV_SKIP_COUNTDOWN",
	DEV_MODE_ACTIVE = "DEV_MODE_ACTIVE",
	DEV_COMMAND_INVALID = "DEV_COMMAND_INVALID",
	DEV_NOT_ALLOWED = "DEV_NOT_ALLOWED",

	-- TOAST
	TOAST_MATCH_STARTING = "TOAST_MATCH_STARTING",
	TOAST_MATCH_ABORTED = "TOAST_MATCH_ABORTED",
	TOAST_RANK_NOT_ELIGIBLE = "TOAST_RANK_NOT_ELIGIBLE",
	TOAST_TELEPORT_ERROR = "TOAST_TELEPORT_ERROR",

	-- FLAVOR (Design Identity compliant)
	FLAVOR_LAST_ONE_STANDING = "FLAVOR_LAST_ONE_STANDING",
	FLAVOR_TRY_AGAIN = "FLAVOR_TRY_AGAIN",
	FLAVOR_OOF = "FLAVOR_OOF",
	FLAVOR_THAT_WAS_CLOSE = "FLAVOR_THAT_WAS_CLOSE",
}

return LocalizationKeys
